### ISSUE TITLE
Regression task - implementation

### ISSUE THREAD

**Issue by Jamie-UoG** [Jamie-UoG/ML_AssEx#2]
We can use this ticket to detail the design and implementation for the regression task.

We need 2 different models, either our own code or from a library, however partial marks are awarded for using external sources.

Each CPU has the following known features:

- Cache memory size. 
- Minimum and maximum number of I/O channels.
- Machine cycle time.
- Minimum and maximum main memory.

The handout suggests using a subset of these features, for example combining minimum and maximum main memory to one value.

The next step we need to take is investigating the different models and choosing 2 to implement.

**Comment by Jamie-UoG** [comment]
Note that the 20% marks for performance are awarded for an average of all our submissions, so we should make sure not to submit too many bad models.

**Comment by Jamie-UoG** [comment]
After some research it looks like we need a "**multi-dimensional polynomial fitting model**".

So the final output can be represented as a polynomial function of the input variables.
[This](https://github.com/mrocklin/multipolyfit/blob/master/multipolyfit/core.py) file from github might be useful as refrence.

**Comment by Jamie-UoG** [comment]
Our first kaggle-test yielded a score of 72.
We used a multivariate-linear model so to improve on this score we should try with a polynomial model instead.

**Comment by Jamie-UoG** [comment]
Trying to implement polynomial regression gives weird results, below is the spread of answers for X_test.csv using a 3rd order polynomial model.

![why](https://user-images.githubusercontent.com/32650073/36605184-e8cb878c-18b7-11e8-9517-81fe325b877a.png)

We think that the weird spikes are due to the fact that some inputs have extremely high CACH compared to others.
One of the ways we might be able to fix this is by changing the CACH to:
`CACH_new = log2(CACH_old)`
e.g
`CACH_old = 256`
`CACH_new = 8 `

**Comment by Jamie-UoG** [comment]
![new](https://user-images.githubusercontent.com/32650073/36622107-674a3140-18f3-11e8-9ef4-44e6f6b31b4c.png)

Fixed this issue by using lasso regression.
Testing this on kaggle got a score of 40.2.

**Comment by kennymurr** [comment]
http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html#sklearn.preprocessing.RobustScaler

Could be useful for removing outliers

**Comment by kennymurr** [comment]
To consider if using L1/L2 regularisation for regression tasks:

l1 and l2 regularizers of linear models) assume that all features are centered around zero and have variance in the same order. If a feature has a variance that is orders of magnitude larger than others, it might dominate the objective function and make the estimator unable to learn from other features correctly as expected. [source](http://scikit-learn.org/stable/modules/preprocessing.html#preprocessing)

**Comment by kennymurr** [comment]
Ensemble https://mlwave.com/kaggle-ensembling-guide/

**Comment by Jamie-UoG** [comment]
Looking at all these different options, the best bet seems like:

**3rd order elastic regression with logarithmic scaling**

At this point we should be looking to subset our input features as per specification and also look into refining our 2 chosen algorithms.

Best score on kaggle is up to 32 now so we should be good for full performance marks.

**Comment by Jamie-UoG** [comment]
New changes are up on regression branch, code is a lot more legible and maintainable now.

**Comment by Jamie-UoG** [comment]
Submission files for regression are now up on regression-sub so i will now merge and close this ticket.

**Comment by Jamie-UoG** [comment]
Submission files merged!
